### ISSUE TITLE
When editing a custom alert, the site selector is not set to the alert's configured site

### ISSUE THREAD

**Issue by diosmosis** [matomo-org/plugin-CustomAlerts#53] opened 2018-12-24 22:13 UTC
Instead it seems to always use the idSite parameter. Which means if you edit an alert and only change one thing, you might accidentally change the site as well.

**Comment by mikky-cecil** [comment] 2021-07-07 07:37
I came here to report this issue, still happening in 2021. I'll just nudge this one instead! :)

We have some critical alerts set up for every site, but unbeknownst to us until today, all of our alerts were only monitoring 1 site due to this bug. (They were set up correctly originally, but someone did a mass edit which accidentally changed each alert's site ID.) Would love to see a fix for this on a plugin we rely on for critical alerts!

### Steps to reproduce

1. On a Matomo instance that tracks multiple sites, create an alert ("My Alert") for one site (Site A).
2. Go to the alerts list, the row containing "My Alert" will correctly have Site A in the "site" column.
3. Navigate to the dashboard and view reports for a different site (Site B). (Just to trigger the `idSite` URL param changing.)
4. Navigate back to the custom alerts page in the settings and edit "My Alert."
5. Notice how the "site" dropdown now incorrectly lists "Site B."
6. Click "save" without editing anything. (Or edit something unrelated to site.)
7. Go back to the alerts list. Notice that even though the user (you) never clicked on the site dropdown, the site was still changed to "Site B."

Hope that helps!

**Comment by sgiehl** [comment] 2021-07-07 08:44
I can confirm this is still the case. Had a quick look at the code and it seems to be a general problem in Matomo and not only this plugin. Will check if it's easy to fix.

**Closed** 2021-07-08 22:41 UTC
Labels: bug

**Comment by mikky-cecil** [comment] 2021-07-09 07:35
Thank you so much for the quick response, @sgiehl !
