### ISSUE TITLE
Custom Alert Eamils are being sent out multiple times for the same alert

### ISSUE THREAD

**Issue by jjcitron** [matomo-org/plugin-CustomAlerts#67] opened 2020-02-24 20:14 UTC
we are running matomo on multiple servers.

we have some alerts setup for things like low conversions

that trigger for the following reason for example:

Conversions is 3 which is less than 5

this alert is getting  triggered 7 times, which is seting out 7 emails to everyone suscribed.

we have tried deleting the report and recreating with the same result.

any insights as to how the job runs and what procesees we shoudl look into would be greatly appreciated.

**Comment by tsteur** [comment] 2020-02-24 20:33
Do you know if browser archiving is disabled? If so, do you run the archiving on multiple servers or only one? Meaning the cronjob that triggers archiving see https://matomo.org/docs/setup-auto-archiving/

**Comment by Marc-Whiteman** [comment] 2020-02-24 21:44
I work with jjcitron, so I'm replying for him here.

Browser archiving is disabled, only one server is running the archive cronjob.

**Comment by dm577** [comment] 2020-02-25 14:50
We saw the same behavior for last night's run. Alerts generated sent 3x emails for each and the individual alerts in the email were also duplicated or triplicated. Using Matomo 3.13.0 with custom alerts 3.0.5 and a 3rd part smtp service is configured for email.

**Comment by tsteur** [comment] 2020-02-25 20:32
Did this behaviour change recently or did you not use it before? Just asking to better understand

**Comment by dm577** [comment] 2020-02-25 20:48
For us, it's been used for a few months at least with no changes other than upgrades to the current Matomo and alerts versions I mentioned in the previous post which have been in place since late November 2019.   The alerts themselves aren't new either.  

After looking at older issues we also checked to see if the alert definitions may have been duped in the alerts table, but those looked ok too.  This was across 23 sites that generated alerts. The time of the emails were all at the same time to the minute for each alert email sent except one which was a minute later. All emails were sent between 12:11-12:22 am so I assume that had to be in the same archive run when it hit scheduled tasks.

**Comment by tsteur** [comment] 2020-02-25 21:04
So the problem seems alerts are marked as sent only at the very end and if multiple processes launch the same task at the same time, it might be sent multiple times. Although maybe the problem is more that maybe multiple processes can start the same task multiple times? This seems to be the actual problem and maybe also the reason we have seen issues before of scheduled reports being sent multiple times.

I'm not 100% sure but it looks like we want `$optionData = Option::get(self::TIMETABLE_OPTION_STRING);` in `core/Scheduler/Timetable.php` to be read and updated more often. For example for each task.

**Comment by jjcitron** [comment] 2020-02-25 21:48
> Did this behaviour change recently or did you not use it before? Just asking to better understand

ever since we first setup alerts, we've seen the multiple emails goign out. granted, its only been a few weeks of using this feature.

**Comment by dm577** [comment] 2020-02-26 00:12
Just to help clarify so something in a fix isn't missed, here's what we saw based on a generic scenario:

Site 1
Alert 1: whatever criteria
Alert 2: whatever criteria

Emails sent:
Site 1 alert email 1
- Alert 1
- Alert 1
- Alert 1
- Alert 2
- Alert 2
- Alert 2

Site 1 alert email 2
- Alert 1
- Alert 1
- Alert 1
- Alert 2
- Alert 2
- Alert 2

... repeat.

So to your point, it seems like the alerts aren't being flagged as complete, but also within the email, the individual alerts are repeated.  So seems to be a flagging type of issue but also may be some logic issue of a loop within a loop.

**Comment by tsteur** [comment] 2020-11-02 21:59
We have merged a fix in Matomo 4. Please comment here if this is still an issue with Matomo 4 and we'll investigate further.

**Closed as completed by tsteur** 2020-11-02 21:59 UTC
Labels: bug
