### ISSUE TITLE
As a Super User, I can't edit the alert created by someone else, although i do get an email notification

### ISSUE THREAD

**Issue by mattab** [matomo-org/plugin-CustomAlerts#82] opened 2020-09-22 20:39 UTC
As a Super User, I can't edit the alert created by someone else, although i do get an email notification.
As a result I can't easily stop the custom alert emails.
I'd expect as a super user to be able to edit any alert.
Here is the email:

![Screenshot from 2020-09-23 08-38-04](https://user-images.githubusercontent.com/466765/93935051-2365d300-fd78-11ea-9a26-7b18b77de1b4.png)

And the screen I get when clicking on the link (logged in as super user):

![Screenshot from 2020-09-23 08-37-50](https://user-images.githubusercontent.com/466765/93935008-15b04d80-fd78-11ea-9ede-e24a172ef329.png)

**Comment by tsteur** [comment] 2020-09-22 20:42
@mattab kind of a duplicate of https://github.com/matomo-org/matomo/issues/15164 but could to have a separate issue for it

**Comment by Stan-vw** [comment] 2024-01-18 04:09
I'd say this falls within the scope of https://github.com/matomo-org/matomo/issues/15164 so closing this as a duplicate. We can reopen if we make it more clearly distinct from the other ticket 👍

**Closed as completed by Stan-vw** 2024-01-18 04:09 UTC
Labels: enhancement
